<feat> default repo

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -13,20 +13,31 @@ jobs:
       - name: Checkout código da PR
         uses: actions/checkout@v4
       - name: Deploy VM Terraform
+        working-directory: terraform
         run: |
           terraform init
           terrafom apply -v "vm_count=1" --auto-aprove
       - name: Get VM IP
         id: vm
+        working-directory: terraform
         run: |
-          VM_IP=$(terraform output -raw vm_ip)
-          echo "VM_IP=$VM_IP" >> $GITHUB_ENV
+          VM_IP=$(terraform output -raw vm_ip 2>/dev/null || true)
+          if [ -z "$VM_IP" ]; then
+            echo "ERROR: terraform output 'vm_ip' is empty. Dumping outputs for debug:"
+            terraform output
+            exit 1
+          fi
+          echo "VM_IP=${VM_IP}" >> $GITHUB_ENV
+
       - name: Run Ansible Playbook
         run: |
-          ansible-playbook playbooks/setup_vm.yml \
-            -i "$VM_IP," \
-            --extra-vars "ansible_user=admin" \
-            --extra-vars "pr_branch=${{ github.head_ref }}"
+          IP="${{ env.VM_IP }}"
+          ansible-playbook playbooks/vm_setup.yml \
+            -i "${IP}," \
+            -u "root" \
+            --ask-pass \
+            --extra-vars "pr_branch=${{ github.head_ref }}" -v
+
       - name: Healthcheck
         run: |
           curl -f http://$VM_IP/healthz
